---
spring:
    profiles.active: test
---
spring:
    profiles: development
    data:
      mongodb.host: localhost
      mongodb.port: 27017
      mongodb.name: cms-db

logging:
    level.org.springframework: INFO
    level.ms.cms: DEBUG

server:
    port: 9000

management:
    port: 9001
---
spring:
    profiles: test
    data:
      mongodb.host: 52.16.117.190
      mongodb.port: 27017
      mongodb.name: cms-db

logging:
    level.org.springframework: INFO
    level.ms.cms: WARN

server:
    port: 8080
    address: 0.0.0.0

management:
    port: 8081
