---
spring:
    profiles.active: test
---
spring:
    profiles: development
    data:
#      mongodb.host: 52.16.117.190
      mongodb.host: 192.168.108.129
      mongodb.port: 27017
      mongodb.name: cms-db

logging:
    level.org.springframework: INFO
    level.sparkle.cms: DEBUG

server:
    port: 9000

management:
    port: 9001

multipart:
    maxFileSize: 30MB
    maxRequestSize: 30MB
---
spring:
    profiles: test
    data:
      mongodb.host: 172.31.10.154
      mongodb.port: 27017
      mongodb.name: cms-db

logging:
    level.org.springframework: INFO
    level.ms.cms: WARN

server:
    port: 80
    address: 0.0.0.0

management:
    port: 8081

mscms:
    authentication:
      dns: ec2-52-17-40-252.eu-west-1.compute.amazonaws.com
      ip: 52.16.40.252
      port: 80
    authoring:
      dns: ec2-52-17-34-133.eu-west-1.compute.amazonaws.com
      ip: 52.16.34.133
      port: 80
    registration:
      dns: ec2-52-16-32-200.eu-west-1.compute.amazonaws.com
      ip: 52.16.32.200
      port: 80
    timeout: 5000

#server.tomcat.compressableMimeTypes=application/json,application/xml
#server.tomcat.compression: on